In [49]:
import numpy as np
import pandas as pd

url = 'https://raw.githubusercontent.com/Kaushik-Varma/mlr/main/Housing.csv'
df = pd.read_csv(url)
print(df.head())

      price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [50]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB
None
              price          area  ...     stories     parking
count  5.450000e+02    545.000000  ...  545.000000  545.000000
mean   4.766729e+06   5150.541284  ...    1.805505    0.693578
std    1.870440e+06   2170.141023  ...    0.867492    0.861586
min    1.750000e+06   1650.000000  ...    1.000000    0.000000
25%    3.430000e+06   3600.000000  ...    1.000000    0.000000
50%    4.340000e+06   4600.000000  ...    2.000000    0.000000
75%    5.740000e+06   6360.000000  ...    2.000000    1.000000
max    1.330000e+07  16200.000000  ...    4.000000    3.000000

[8 rows x 6 columns]

In [51]:
# Converting the categorical variable into numerical
varlist = ['mainroad', 'guestroom', 'basement', 'airconditioning', 
           'hotwaterheating',
           'prefarea']

# Defining the map function
def binary_map(x):
  return x.map({'yes': 1, 'no': 0})

# Applying the function to the df list
df[varlist] = df[varlist].apply(binary_map)

# Check the housing dataframe now
df

        price  area  bedrooms  ...  parking  prefarea  furnishingstatus
0    13300000  7420         4  ...        2         1         furnished
1    12250000  8960         4  ...        3         0         furnished
2    12250000  9960         3  ...        2         1    semi-furnished
3    12215000  7500         4  ...        3         1         furnished
4    11410000  7420         4  ...        2         0         furnished
..        ...   ...       ...  ...      ...       ...               ...
540   1820000  3000         2  ...        2         0       unfurnished
541   1767150  2400         3  ...        0         0    semi-furnished
542   1750000  3620         2  ...        0         0       unfurnished
543   1750000  2910         3  ...        0         0         furnished
544   1750000  3850         3  ...        0         0       unfurnished

[545 rows x 13 columns]